---
title: "NBA Connections: PUG Blog Post"
author: "Emma Gardecki and Eric Ingram"
date: "May 18, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggnetwork)
library(igraph)
library(ggiraph)
library(ggplot2)
library(plotly)
```

```{r, echo=FALSE}
#import dataset
path_in <- "/Users/emmagardecki/Documents/junior yr/stat231/Blog-Team-Basketball"
draft <- read_csv(paste0(path_in, "/draft_allplayers.csv"))
players <- read_csv(paste0(path_in, "/allPlayers2010-2021.csv"))
TEAMS0 <- c("ATL", "BOS", "NJN", "BKK", "CHA", "CHI", "CLE", "DAL", "DEN", "DET", "GSW", "HOU", "IND", "LAC", "LAL", "MEM", "MIA", "MIL", "MIN", "NOP", "NYK", "OKC", "ORL", "PHI", "PHX", "POR", "SAC", "SAS", "TOR", "UTA", "WAS", "CHO", "NOH")
```

```{r, warning = FALSE}
#build prelim college network
draft_college <- draft %>%
  select(College, Player)

college_graph <- graph_from_data_frame(draft_college, directed = FALSE)

college_ntwrk <- ggnetwork(college_graph)

ggplot(data = college_ntwrk
       , aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey50") +
  geom_nodes() +
  # geom_nodelabel(aes(label = name)) +
  theme_blank()

diameter(college_graph)
vcount(college_graph)
ecount(college_graph)
```

```{r, warning = FALSE, fig.height=4.0, fig.width=8.0}
####HOW CONNECTED NBA TEAMS ARE

set.seed(2000)

#build prelim nba network
draft_nba <- players %>%
  filter(Year == 2019) %>%
  select(player, Team, Year)
  # filter(Team == "BOS" )

nba_graph <- graph_from_data_frame(draft_nba, directed = FALSE)

nba_ntwrk <- ggnetwork(nba_graph)

ggplot(data = nba_ntwrk
       , aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges( color = "green") +
  geom_nodes() +
  geom_nodelabel(aes(label = name)) +
  theme_blank()

diameter(nba_graph)
vcount(nba_graph)
ecount(nba_graph)
```


```{r, warning = FALSE}
#build prelim hs network
draft_hs <- draft %>%
  select(HS, Player, Pick)

hs_graph <- graph_from_data_frame(draft_hs, directed = FALSE)

hs_ntwrk <- ggnetwork(hs_graph)

ggplot(data = hs_ntwrk
       , aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "green") +
  geom_nodes() +
  # geom_nodelabel(aes(label = name)) +
  theme_blank()


diameter(hs_graph)
vcount(hs_graph)
ecount(hs_graph)
```







```{r, warning = FALSE, fig.height=4.0, fig.width=8.0}
####NBA PLAYERS BY YR

set.seed(2001)

#build prelim nba network
draft_nba1 <- players %>%
  select(player, Team, Year) %>%
  filter(Year == "2010" )

nba_graph1 <- graph_from_data_frame(draft_nba1, directed = FALSE)

nba_ntwrk1 <- ggnetwork(nba_graph1)

ggplot(data = nba_ntwrk1
       , aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(arrow=arrow(type="closed", length=unit(6,"pt"))
            , color = "lightgray") +
  geom_nodes() +
  geom_nodelabel(aes(label = name)) +
  theme_blank()

diameter(nba_graph1)
vcount(nba_graph1)
ecount(nba_graph1)
```







```{r, warning = FALSE}
set.seed(001)
draft_nba <- players %>%
  select(player, Team, Year) 

nba_graph <- graph_from_data_frame(draft_nba, directed = FALSE)

nba_ntwrk <- ggnetwork( nba_graph )
nba_ntwrk$tooltip <- paste0("Player = ", nba_ntwrk$name)
  
gg_point_1 <- ggplot(data = nba_ntwrk
       , aes(x = x, y = y, xend = xend, yend = yend, tooltip = tooltip)) +
  geom_edges(color = "grey50") +
  geom_nodes(color = "orange", size = 4) +
  theme_blank() +
  # geom_nodetext(aes(label = name)) +
  geom_point_interactive(size=2)

# htmlwidget call
ggiraph(code = {print(gg_point_1)})
```


```{r, warning = FALSE}
set.seed(002)
hs <- players %>%
  select(player, HS, Year) 

hsg <- graph_from_data_frame(hs, directed = FALSE)

hsnet <- ggnetwork( hsg )
hsnet$tooltip <- paste0("Player = ", hsnet$name)
  
gg_point_2 <- ggplot(data = hsnet
       , aes(x = x, y = y, xend = xend, yend = yend, tooltip = tooltip)) +
  geom_edges(color = "green") +
  geom_nodes(color = "red", size = 4) +
  theme_blank() +
  # geom_nodetext(aes(label = name)) +
  geom_point_interactive(size=2)

# htmlwidget call
ggiraph(code = {print(gg_point_2)})
```

```{r, warning = FALSE}
set.seed(0034)
c <- players %>%
  select(player, college, Year) 

collg <- graph_from_data_frame(c, directed = FALSE)

collnet <- ggnetwork( collg )
collnet$tooltip <- paste0("Player = ", collnet$name)
  
gg_point_3 <- ggplot(data = collnet
       , aes(x = x, y = y, xend = xend, yend = yend, tooltip = tooltip)) +
  geom_edges(color = "green") +
  geom_nodes(color = "gold", size = 4) +
  theme_blank() +
  # geom_nodetext(aes(label = name)) +
  geom_point_interactive(size=2)

# htmlwidget call
ggiraph(code = {print(gg_point_3)})
```

```{r, warning = FALSE}
set.seed(0034)
nba10 <- players %>%
  select(player, Team, Year) %>%
  filter( Year == "2010")

nbag10 <- graph_from_data_frame(nba10, directed = TRUE)

nbanet10 <- ggnetwork( nbag10 )
nbanet10$tooltip <- paste0("Player = ", nbanet10$name)
  
gg10 <- ggplot(data = nbanet10
       , aes(x = x, y = y, xend = xend, yend = yend, tooltip = tooltip)) +
  geom_edges(color = "green") +
  geom_nodes(color = "gold", size = 4) +
  theme_blank() +
  geom_nodetext(aes(label = name %in% TEAMS0), check_overlap = TRUE) +
  geom_point_interactive(size=2) + 
  labs(
    title = "2010 NBA Season Trades"
  )

# htmlwidget call
# ggiraph(code = {print(gg_point_4)})

girafe(ggobj = gg10, 
  options = list(
    opts_sizing(width = .7),
    opts_hover_inv(css = "opacity:0.1;"),
    opts_hover(css = "fill:red;"),
    opts_toolbar(position = "bottomright") )
  )
```

```{r, warning = FALSE}
set.seed(0035)
nba11 <- players %>%
  select(player, Team, Year) %>%
  filter( Year == "2011")

nbag11 <- graph_from_data_frame(nba11, directed = TRUE)

nbanet11 <- ggnetwork( nbag11 )
nbanet11$tooltip <- paste0("Player = ", nbanet11$name)
  
gg11 <- ggplot(data = nbanet11
       , aes(x = x, y = y, xend = xend, yend = yend, tooltip = tooltip)) +
  geom_edges(color = "green") +
  geom_nodes(color = "gold", size = 4) +
  theme_blank() +
  # geom_nodetext(aes(label = name)) +
  geom_point_interactive(size=2) + 
  labs(
    title = "2011 NBA Season Trades"
  )

# htmlwidget call
# ggiraph(code = {print(gg_point_4)})

girafe(ggobj = gg11, 
  options = list(
    opts_sizing(width = .7),
    opts_hover_inv(css = "opacity:0.1;"),
    opts_hover(css = "fill:red;"),
    opts_toolbar(position = "bottomright") )
  )
```


```{r, warning = FALSE}
set.seed(0036)
nba12 <- players %>%
  select(player, Team, Year) %>%
  filter( Year == "2012")

nbag12 <- graph_from_data_frame(nba12, directed = TRUE)

nbanet12 <- ggnetwork( nbag12 )
nbanet12$tooltip <- paste0("Player = ", nbanet12$name)
  
gg12 <- ggplot(data = nbanet12
       , aes(x = x, y = y, xend = xend, yend = yend, tooltip = tooltip)) +
  geom_edges(color = "green") +
  geom_nodes(color = "gold", size = 4) +
  theme_blank() +
  # geom_nodetext(aes(label = name)) +
  geom_point_interactive(size=2) + 
  labs(
    title = "2012 NBA Season Trades"
  )

# htmlwidget call
# ggiraph(code = {print(gg_point_4)})

girafe(ggobj = gg12, 
  options = list(
    opts_sizing(width = .7),
    opts_hover_inv(css = "opacity:0.1;"),
    opts_hover(css = "fill:red;"),
    opts_toolbar(position = "bottomright") )
  )
```

```{r, warning = FALSE}
p0 <- c("Rajon Rondo", "Kyle Lowry", "JJ Redick", "Paul Millsap", "LaMarcus Aldridge", "Rudy Gay")
set.seed(0037)
nbaRR <- players %>%
  select(player, Team, Year) %>%
  filter( player %in% p0)

RR <- graph_from_data_frame(nbaRR, directed = TRUE)

RRnet <- ggnetwork( RR )
RRnet$tooltip <- paste0("Team = ", RRnet$name)
  
RRgg <- ggplot(data = RRnet
       , aes(x = x, y = y, xend = xend, yend = yend, tooltip = tooltip)) +
  geom_edges(color = "green") +
  geom_nodes(color = "gold", size = 4) +
  theme_blank() +
  # geom_nodetext(aes(label = draft$name)) +
  geom_point_interactive(size=2) + 
  labs(
    title = "Rajon Rondo Connectivity"
  )

# htmlwidget call
# ggiraph(code = {print(gg_point_4)})

girafe(ggobj = RRgg, 
  options = list(
    opts_sizing(width = .7),
    opts_hover_inv(css = "opacity:0.1;"),
    opts_hover(css = "fill:red;"),
    opts_toolbar(position = "bottomright") )
  )
```

```{r, warning = FALSE}
set.seed(0049)
coll <- players %>%
  select(player, college, Year) 

c0 <- graph_from_data_frame(coll, directed = TRUE)

collnet <- ggnetwork( c0 )
collnet$tooltip <- paste0("Player = ", collnet$name)
  
college <- ggplot(data = collnet
       , aes(x = x, y = y, xend = xend, yend = yend, tooltip = tooltip)) +
  geom_edges(color = "royalblue2") +
  geom_nodes(color = "firebrick2", size = 4) +
  theme_blank() +
  # geom_nodetext(aes(label = name)) +
  geom_point_interactive(size=2) + 
  labs(
    title = "college network"
  )

girafe(ggobj = college, 
  options = list(
    opts_sizing(width = .7),
    opts_hover_inv(css = "opacity:0.1;"),
    opts_hover(css = "fill:red;"),
    opts_toolbar(position = "bottomright") )
  )
```





##SUCCESS####################################################

```{r, eval=FALSE}
library(plotly)
get_data <- reactive({
    event.data <- event_data("plotly_selected", source = "subset")
    data <- draft %>% mutate(show_id = FALSE)
    if (!is.null(event.data)) {
      data$show_id[event.data$pointNumber + 1] <- TRUE
    }
    data
  })

renderPlotly({
    data <- get_data()
    p <- ggplot(data, aes(x = Years, y = input$yaxchoices, size = Pick, key = Player)) +
      geom_point(aes(color = "royalblue2"), position = "jitter") + 
      geom_text(data=subset(data, show_id),aes( Years, PTS, label= Player)
                , position = position_jitter(width = 20,height = 20), show.legend = FALSE) +
      labs(x = "Length of career", y = yax_choice_names[yax_choice_values == input$yaxchoices]
           , title = paste0("Career ", yax_choice_names[yax_choice_values == input$yaxchoices])
           , subtitle = paste0(input$plotyearvar, " Draft Class")
           , size = (size_choice_names[size_choice_values == input$sizechoices])) +
      guides(color = FALSE) +
      theme( axis.title = element_text(face = "bold"))
    ggplotly(p, source = "subset") %>% layout(dragmode = "select")
  })

p
```


```{r, warning=FALSE}
##FGpct
plot_ly( draft, x = ~Years, y = ~FGpct, type = "scatter", name = ~Player) %>%
  add_trace(draft, color = ~as.factor(Draft_Year)) %>%
  layout(title = "Career Success - Field Goal %", showlegend = FALSE)
```

```{r}
##VORP
plot_ly( draft, x = ~Years, y = ~VORP, type = "scatter", name = ~Player) %>%
  add_trace(draft, color = ~as.factor(Draft_Year)) %>%
  layout(title = "Career Success - Value Over Replacement Player", showlegend = FALSE)
```

```{r}
##TRB
plot_ly( draft, x = ~Years, y = ~TRB, type = "scatter", name = ~Player) %>%
  add_trace(draft, color = ~as.factor(Draft_Year)) %>%
  layout(title = "Career Success - Rebounds per Game", showlegend = FALSE)
```

```{r}
##PTS
plot_ly( draft, x = ~Years, y = ~PTS, type = "scatter", name = ~Player) %>%
  add_trace(draft, color = ~as.factor(Draft_Year)) %>%
  layout(title = "Career Success - Points per Game", showlegend = FALSE)
```

```{r}
##BPM
plot_ly( draft, x = ~Years, y = ~BPM, type = "scatter", name = ~Player) %>%
  add_trace(draft, color = ~as.factor(Draft_Year)) %>%
  layout(title = "Career Success - Box Plus/Minus", showlegend = FALSE)
```







